---
- name: Create a directory /etc/frpc for .ini
  ansible.builtin.file:
    path: /etc/frpc
    state: directory
    mode: '0755'
- name: copy executable
  copy:
    src: "frpc"
    dest: "/opt/frpc/"
    mode: 0755
- name: Generate "frpc.ini"
  template: 
    src: "templates/frpc.ini.j2"
    dest: "/etc/frpc/frpc.ini"
    mode: 0666
- name: copy unit
  copy:
    src: "frpc.service"
    dest: "/etc/systemd/system/"
    mode: 0666
- name: configure frpc service
  systemd:
    name: frpc
    daemon_reload: true
    state: started
    enabled: true

...
