---
- name: install FastReverseProxyServer
  hosts: vhaws_gw
  become: yes
  tasks:
    - name: include install frp server role
      include_role:
        name: frps

- name: install FastReverseProxyClient, SteamCMD and Valheim server
#current ini file is for Valheim Dedicated server
  hosts: vhaws_gh
  roles:
    - frpc
    - ansible-role-steamcmd
    - valheim-setup
  become: yes

- name : setup ssh
  hosts: vhaws
  become: yes
  roles:
    - ssh-key-share

- name: install FastReverseProxyServer
  hosts: vhaws_gw
  become: yes
  roles:
    - tgbot
  # tasks:
  #   - name: include install tgbot server role
  #     include_role:
  #       name: tgbot


  
...

